### ISSUE TITLE
3.6.1版本报错

### ISSUE THREAD

**Issue by mcyydscc** [IShiraiKurokoI/CTFd-Matrix-Scoreboard#1]
![image](https://github.com/IShiraiKurokoI/CTFd-Matrix-Scoreboard/assets/90653809/356813e9-6570-4e4b-b0fb-0c2742a6418f)
![image](https://github.com/IShiraiKurokoI/CTFd-Matrix-Scoreboard/assets/90653809/74fff2c8-858d-429c-b764-c548fa89230a)

**Comment by IShiraiKurokoI** [comment]
emmmm，这个sid字段是我们自己魔改过的平台使用的一个数据，对应的那段代码我待会注释掉

**Comment by IShiraiKurokoI** [comment]
我把sid字段都注释掉了，现在应该没问题了 
1e799d8242c3c4c928fddb83a5da231082136587

**Comment by mcyydscc** [comment]
core主题恢复了，core-beta主题好像没有加载进css
![image](https://github.com/IShiraiKurokoI/CTFd-Matrix-Scoreboard/assets/90653809/2e25ef1c-28be-405d-9050-81d05b6e1944)

**Comment by IShiraiKurokoI** [comment]
> core主题恢复了，core-beta主题好像没有加载进css ![image](https://private-user-images.githubusercontent.com/90653809/298322698-2e25ef1c-28be-405d-9050-81d05b6e1944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDYwMzAsIm5iZiI6MTcwNTgwNTczMCwicGF0aCI6Ii85MDY1MzgwOS8yOTgzMjI2OTgtMmUyNWVmMWMtMjhiZS00MDVkLTkwNTAtODFkMDViNmUxOTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAyNTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjA0YzVhNzg3MGVmZDdlNDcxNWVjOWNhNjVhZTIyMzc2N2EwODM3NDZhNjdiNTExZDZhNjAwZDc1YzU3YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIP1eFDdMvlydOseiyZUSdIwzX9WmdYgV_3XfDbvuHA)

core-beta是3.6的重构的新主题，用的是bootstrap5，模板架构也变了，理论上如果用那个前端主题的话，所有前端模板都需要重写，你可以自己改一下。（实际上大部分3.6之前开发的但凡有前端的插件到了3.6的默认core-beta主题基本都会出现问题）
