### ISSUE TITLE
排名错误

### ISSUE THREAD

**Issue by mcyydscc** [IShiraiKurokoI/CTFd-Matrix-Scoreboard#2]
计分板的排名错误，和导出的不相符，而且点进去显示的排名也不一样
![image](https://github.com/IShiraiKurokoI/CTFd-Matrix-Scoreboard/assets/90653809/5235f4cd-ceac-4769-98b9-8fc7d5e8a4fc)
![image](https://github.com/IShiraiKurokoI/CTFd-Matrix-Scoreboard/assets/90653809/ba4f5595-2bff-4de4-8d69-1a694c9fdc36)
![image](https://github.com/IShiraiKurokoI/CTFd-Matrix-Scoreboard/assets/90653809/4940dcd7-cea2-4ee8-9802-021c00d08d99)

**Comment by IShiraiKurokoI** [comment]
有一二三血加分加成，如果不需要这个功能可以在init里将其注释掉，分数就是原始数据了，1-5都是600分，没区别啊
